Update ocp_4.0.md
hongkailiu/svt-case-doc pull request #3
Opened 2019-02-01 19:54 UTC by wabouhamad

added section for how to modify kubeletArgument maxPods

2019-02-01 20:03 UTC, wabouhamad commented
@hongkailiu PTAL

2019-02-01 20:48 UTC, hongkailiu requested changes
Thanks for the PR.
Considering the length of the content, I would make its own md file (`max_pods.md`?) and use the link in this page.
I can do this too after your PR get merged.

2019-02-01 20:48 UTC, hongkailiu commented on ocp_4.0/ocp_4.0.md
> +The default value for maxPods on all the nodes is 250 pods.  In order to change it, you'll need to first create a KubeletConfig CRD and then apply it.
CRD -> CR

2019-02-01 20:48 UTC, hongkailiu commented on ocp_4.0/ocp_4.0.md
> +Create the following CRD with the desired value for maxPods, and label for the mahcineConfigPool selector, set to "custom-kubelet: large-pods"
CRD -> CR

2019-02-01 20:48 UTC, hongkailiu commented on ocp_4.0/ocp_4.0.md
> +add:
I would take the command into ``` ... ``` for better formatting.

2019-02-01 20:48 UTC, hongkailiu commented on ocp_4.0/ocp_4.0.md
> +.
I would use `...` instead of
.
.
.

2019-02-01 20:48 UTC, hongkailiu commented on ocp_4.0/ocp_4.0.md
> +Apply the KubeletConfig CRD to force the change to the maxPods value on all the worker nodes:
CRD -> CR

2019-02-01 20:48 UTC, hongkailiu commented on ocp_4.0/ocp_4.0.md
> +Also as a result of applyin the kubeltconfig CRD, a new managed worker machineconfig "99-worker-<....>-kubelet" is created:
CRD -> CR

2019-02-02 03:04 UTC, wabouhamad commented
@hongkailiu made suugested updates, PTAL or merge if ok.  Thx

2019-02-04 14:41 UTC, hongkailiu approved these changes

2019-02-04 14:42 UTC, merged